name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Download landscape theme
        run: git clone https://github.com/hexojs/hexo-theme-landscape.git themes/landscape

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      # 安装 Pandoc（解决 hexo-renderer-pandoc 找不到 pandoc 的问题）
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: node node_modules/hexo/bin/hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force: true
