name: Deploy Hexo Blog

on:
  push:
    branches:
      - main  # 或你的默认分支名

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5   # 1. 升级到 v5

      - name: Download landscape theme
        run: git clone https://github.com/hexojs/hexo-theme-landscape.git themes/landscape

      - name: Setup Node.js
        uses: actions/setup-node@v5   # 2. 升级到 v5
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npx hexo generate   # 3. 使用 npx

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
